--------------------------------------------------------
--  File created - «·Œ„Ì”-√»—Ì·-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "NOVUS"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM_CLIENT" VARCHAR2(20 BYTE), 
	"PRENOM_CLIENT" VARCHAR2(20 BYTE), 
	"CIN_CLIENT" NUMBER, 
	"EMAIL_CLIENT" VARCHAR2(20 BYTE), 
	"TELEPHONE_CLIENT" NUMBER, 
	"ADRESSE_CLIENT" VARCHAR2(20 BYTE), 
	"METIER_CLIENT" VARCHAR2(20 BYTE), 
	"DATE_INSCRIPTION_CLIENT" DATE, 
	"ID_EMPLOYE" NUMBER, 
	"MDP_EMPLOYE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "NOVUS"."EMPLOYES" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM_EMPLOYE" VARCHAR2(20 BYTE), 
	"PRENOM_EMPLOYE" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE_EMPLOYE" DATE, 
	"EMAIL_EMPLOYE" VARCHAR2(50 BYTE), 
	"TELEPHONE_EMPLOYE" NUMBER, 
	"ADRESSE_EMPLOYE" VARCHAR2(20 BYTE), 
	"DATE_EMBAUCHE_EMPLOYE" DATE, 
	"POSTE_EMPLOYE" VARCHAR2(20 BYTE), 
	"SALAIRE_EMPLOYE" NUMBER, 
	"MPD_EMPLOYE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENTS
--------------------------------------------------------

  CREATE TABLE "NOVUS"."EVENEMENTS" 
   (	"ID_EVENEMENT" NUMBER, 
	"NOM_EVENEMENT" VARCHAR2(20 BYTE), 
	"DATE_DEBUT_EVENEMENT" DATE, 
	"DATE_FIN_EVENEMENT" VARCHAR2(20 BYTE), 
	"NBR_PARTICIPANTS_EVENEMENT" NUMBER, 
	"ADRESSE_EEVENEMENT" VARCHAR2(20 BYTE), 
	"DESCRIPTION_EVENEMENT" VARCHAR2(200 BYTE), 
	"TYPE_EVENEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORGANISATIONS
--------------------------------------------------------

  CREATE TABLE "NOVUS"."ORGANISATIONS" 
   (	"ID_EMPLOYE" NUMBER, 
	"ID_EVENEMENT" NUMBER, 
	"DATE_DEBUT_EVENEMENT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJET
--------------------------------------------------------

  CREATE TABLE "NOVUS"."PROJET" 
   (	"ID_PROJET" NUMBER, 
	"NOM_PROJET" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"BUDGET_PROJET" NUMBER, 
	"SECTEUR_PROJET" VARCHAR2(20 BYTE), 
	"STATUS_PROJET" VARCHAR2(20 BYTE), 
	"COUT_PROJET" NUMBER, 
	"ADRESSE_PROJET" VARCHAR2(20 BYTE), 
	"DESCRIPTION_PROJET" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESSOURCES
--------------------------------------------------------

  CREATE TABLE "NOVUS"."RESSOURCES" 
   (	"ID_RESSOURCE" NUMBER, 
	"NOM_RESSOURCE" VARCHAR2(20 BYTE), 
	"TYPE_RESSOURCE" VARCHAR2(20 BYTE), 
	"QUANTITE_RESSOURCE" NUMBER, 
	"COUT_RESSOURCE" NUMBER, 
	"ID_PROJET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NOVUS.CLIENT
SET DEFINE OFF;
REM INSERTING into NOVUS.EMPLOYES
SET DEFINE OFF;
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (11649668,'meh','ghabri',to_date('01-01-00','DD-MM-RR'),'mehyarghabri11@gmail.com',65986598,'maknessy',to_date('01-01-00','DD-MM-RR'),'admin',7000,'123456789');
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (6565,'yasmine','benchalbi',to_date('01-01-00','DD-MM-RR'),'yasmine@gmail.com',25896321,'marsa',to_date('01-01-00','DD-MM-RR'),'employe',8000,null);
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (898,'sabrine','ouesleti',to_date('16-04-04','DD-MM-RR'),'sabrine@gmail.com',98989898,'marsa',to_date('16-04-25','DD-MM-RR'),'RH',5500,null);
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (98,'dhia','borzli',to_date('01-01-04','DD-MM-RR'),'dhia@gmail.com',98989898,'marsa',to_date('01-01-00','DD-MM-RR'),'employe',10000,'569898');
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (78,'ahmed','ben mahmoud',to_date('01-01-00','DD-MM-RR'),'ahmed@gmail.com',65656565,'marsa',to_date('01-01-00','DD-MM-RR'),'admin',6500,null);
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (1551,'louay','hamdaoui',to_date('01-01-04','DD-MM-RR'),'louay@gmail.com',65989865,'maknessy',to_date('01-01-14','DD-MM-RR'),'RH',2000,null);
Insert into NOVUS.EMPLOYES (ID_EMPLOYE,NOM_EMPLOYE,PRENOM_EMPLOYE,DATE_NAISSANCE_EMPLOYE,EMAIL_EMPLOYE,TELEPHONE_EMPLOYE,ADRESSE_EMPLOYE,DATE_EMBAUCHE_EMPLOYE,POSTE_EMPLOYE,SALAIRE_EMPLOYE,MPD_EMPLOYE) values (6556,'sajed','badraoui',to_date('16-04-90','DD-MM-RR'),'sajed@gmail.com',58965896,'maknessy',to_date('16-04-25','DD-MM-RR'),'ingenieur',900,null);
REM INSERTING into NOVUS.EVENEMENTS
SET DEFINE OFF;
REM INSERTING into NOVUS.ORGANISATIONS
SET DEFINE OFF;
REM INSERTING into NOVUS.PROJET
SET DEFINE OFF;
REM INSERTING into NOVUS.RESSOURCES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RESSOURCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOVUS"."RESSOURCES_PK" ON "NOVUS"."RESSOURCES" ("ID_RESSOURCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOVUS"."EVENEMENTS_PK" ON "NOVUS"."EVENEMENTS" ("ID_EVENEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOVUS"."CLIENT_PK" ON "NOVUS"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOVUS"."TABLE1_PK" ON "NOVUS"."PROJET" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOVUS"."EMPLOYES_PK" ON "NOVUS"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESSOURCES
--------------------------------------------------------

  ALTER TABLE "NOVUS"."RESSOURCES" MODIFY ("ID_RESSOURCE" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."RESSOURCES" MODIFY ("TYPE_RESSOURCE" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."RESSOURCES" ADD CONSTRAINT "RESSOURCES_PK" PRIMARY KEY ("ID_RESSOURCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENEMENTS
--------------------------------------------------------

  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("ID_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" ADD CONSTRAINT "EVENEMENTS_PK" PRIMARY KEY ("ID_EVENEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("NOM_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("DATE_DEBUT_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("DATE_FIN_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("NBR_PARTICIPANTS_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("ADRESSE_EEVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("DESCRIPTION_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EVENEMENTS" MODIFY ("TYPE_EVENEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "NOVUS"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "NOVUS"."EMPLOYES" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJET
--------------------------------------------------------

  ALTER TABLE "NOVUS"."PROJET" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("ID_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("NOM_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("BUDGET_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("SECTEUR_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("COUT_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("ADRESSE_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("DESCRIPTION_PROJET" NOT NULL ENABLE);
  ALTER TABLE "NOVUS"."PROJET" MODIFY ("STATUS_PROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "NOVUS"."CLIENT" ADD CONSTRAINT "CLIENT_FK" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "NOVUS"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANISATIONS
--------------------------------------------------------

  ALTER TABLE "NOVUS"."ORGANISATIONS" ADD CONSTRAINT "FK1" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "NOVUS"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "NOVUS"."ORGANISATIONS" ADD CONSTRAINT "FK2" FOREIGN KEY ("ID_EVENEMENT")
	  REFERENCES "NOVUS"."EVENEMENTS" ("ID_EVENEMENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJET
--------------------------------------------------------

  ALTER TABLE "NOVUS"."PROJET" ADD CONSTRAINT "PROJET_FK" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "NOVUS"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESSOURCES
--------------------------------------------------------

  ALTER TABLE "NOVUS"."RESSOURCES" ADD CONSTRAINT "RESSOURCES_FK" FOREIGN KEY ("ID_PROJET")
	  REFERENCES "NOVUS"."PROJET" ("ID_PROJET") ENABLE;
